### ISSUE TITLE
erreur cURL/ZIP

### ISSUE THREAD

**Issue by C0LiSii0N** [MineWeb/MineWebCMS#134]
Salut, je viens de mettre le testeur de compatibilité sur mon site, et il me dit que cURL et unzip ne sont pas installé alors que ils le sont bel et bien.

**Comment by DarkScientist** [comment]
Hello, Quel est hebergeur ? Web ? VPS ? Je penses que tu es sous VPS, et il faut que tu aies installé phpcurl. Si tu l'as déjà installé, on verra par la suite. Pour un support plus instantané, n'hésite pas à passer sur le discord : https://discord.gg/uuz83hxEnvoyé depuis mon mobile Huawei-------- Message original --------Objet : [MineWeb/MineWebCMS] erreur cURL/ZIP (#134)De : C0LiSii0N À : MineWeb/MineWebCMS Cc : Subscribed Salut, je viens de mettre le testeur de compatibilité sur mon site, et il me dit que cURL et unzip ne sont pas installé alors que ils le sont bel et bien.



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/MineWeb/MineWebCMS/issues/134",

"url": "https://github.com/MineWeb/MineWebCMS/issues/134",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
